services:
  init-container:
    image: busybox
    volumes:
      - proxy_cache:/var/rescue-proxy
      - api_state:/var/lib/rescue-api
    command:
      - /bin/sh
      - -c
      - "chown -R ${RESCUE_PROXY_UID:-65534}:${RESCUE_PROXY_GID:-65534} /var/rescue-proxy && chown -R ${RESCUE_API_UID:-65534}:${RESCUE_API_GID:-65534} /var/lib/rescue-api"

  rescue-proxy:
    restart: unless-stopped
    user: "${RESCUE_PROXY_UID:-65534}:${RESCUE_PROXY_GID:-65534}"
    image: rocketrescuenode/rescue-proxy:latest
    ports: [ "55052:5052" ]
    volumes:
      - proxy_cache:/var/rescue-proxy
    command:
      - -bn-url
      - http://x.x.x.x:5052
      - -ec-url
      - ws://x.x.x.x:8546
      - -addr
      - 0.0.0.0:5052
      - -debug
      - -api-addr
      - 0.0.0.0:9081
      - -cache-path
      - /var/rescue-proxy
      - -rocketstorage-addr
      - 0x594Fb75D3dc2DFa0150Ad03F99F97817747dd4E1
      - -hmac-secret
      - JTGZSMY06rP4lNSf0U98F6Wi/ENJJg6xSbiddSp5xO8=
    depends_on:
      init-container:
        condition: service_completed_successfully

  rescue-api:
    restart: unless-stopped
    user: "${RESCUE_API_UID:-65534}:${RESCUE_API_GID:-65534}"
    image: rocketrescuenode/rescue-api:latest
    ports: [ "50080:8080" ]
    volumes:
      - api_state:/var/lib/rescue-api
    command:
      - -debug
      - -secure-grpc=false
      - -addr
      - 0.0.0.0:8080
      - -allowed-origins
      - "*"
      - -rescue-proxy-api-addr
      - "rescue-proxy:9081"
      - -db-path
      - /var/lib/rescue-api/db.sqlite3
      - -hmac-secret
      - JTGZSMY06rP4lNSf0U98F6Wi/ENJJg6xSbiddSp5xO8=
    depends_on:
      init-container:
        condition: service_completed_successfully
volumes:
  proxy_cache:
  api_state:
